# Generated by Django 5.0.2 on 2024-02-21 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engLearn', '0001_initial'),
        ('studying_now', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studyingnowmodel',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='studyingnowmodel',
            name='studying_now_word',
        ),
        migrations.AddField(
            model_name='studyingnowmodel',
            name='studying_now_word',
            field=models.ManyToManyField(related_name='studying_now_word', to='engLearn.words'),
        ),
    ]
