# Generated by Django 5.0.2 on 2024-02-13 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_word', models.CharField(max_length=45)),
                ('ru_word', models.CharField(max_length=45)),
                ('en_example', models.TextField()),
                ('ru_example', models.TextField()),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
