# Generated by Django 5.0.2 on 2024-02-13 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engLearn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='words',
            name='gap',
            field=models.CharField(default=None, max_length=5),
        ),
        migrations.AddField(
            model_name='words',
            name='picau',
            field=models.CharField(default=None, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='words',
            name='picurl',
            field=models.TextField(blank=True),
        ),
    ]
